# Generated by Django 3.2.7 on 2021-12-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='peace',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='rescue',
            field=models.BooleanField(null=True),
        ),
    ]
